[mongodb]
mongodb-dev.abstractglobal.online                  #mongodb domain name

[catalogue]
catalogue-dev.abstractglobal.online               #catalogue domain name

[redis]
redis-dev.abstractglobal.online                 #redis domain name

[user]
user-dev.abstractglobal.online                  #user domain name

[cart]
cart-dev.abstractglobal.online                  #cart domain name

[mysql]
mysql-dev.abstractglobal.online                 #mysql domain name

[shipping]
shipping-dev.abstractglobal.online             #shipping domain name

[rabbitmq]
rabbitmq-dev.abstractglobal.online             #rabbitmq domain name

[payment]
payment-dev.abstractglobal.online             #payment domain name

[frontend]
frontend-dev.abstractglobal.online           #frontend domain name

[all:vars]                        #Inventory variable which can be used at playbooks as well
ansible_user=ec2-user
ansible_password=DevOps321
MONGODB_HOST=mongodb-dev.abstractglobal.online
CATALOGUE_HOST=catalogue-dev.abstractglobal.online
REDIS_HOST=redis-dev.abstractglobal.online
USER_HOST=user-dev.abstractglobal.online
CART_HOST=cart-dev.abstractglobal.online
MYSQL_HOST=mysql-dev.abstractglobal.online
SHIPPING_HOST=shipping-dev.abstractglobal.online
RABBITMQ_HOST=rabbitmq-dev.abstractglobal.online
PAYMENT_HOST=payment-dev.abstractglobal.online